const clips = [
  {
    title: `Who Gets To Be Bossypants? On Class and Privilege in Female Comedians’ Memoirs`,
    link: "https://lithub.com/who-gets-to-be-bossypants-on-class-and-privilege-in-female-comedians-memoirs/",
    publication: "Literary Hub",
    date: "August 27, 2021",
    photo: "./assets/bossypants.jpg",
  },
  {
    title: `Paying In Time`,
    link: "https://therumpus.net/2021/06/paying-in-time/",
    publication: "The Rumpus",
    date: "June 29, 2021",
    photo: "./assets/paying-in-time.jpg",
  },
  {
    title: `Childcare is essential for essential workers, but what if you’re not one of them?`,
    link: "https://bklyner.com/childcare-is-essential-for-essential-workers-but-what-if-youre-not-one-of-them/",
    publication: "Bklyner",
    date: "May 19, 2020",
    photo: "./assets/childcare-workers.jpg",
  },
  {
    title: `Falling in Love With a Balloon Artist Taught Me I Never Wanted to Be “Normal”`,
    link: "https://catapult.co/stories/falling-in-love-with-a-balloon-artist-taught-me-i-never-wanted-to-be-normal-essay-sarah-jaffe",
    publication: "Catapult",
    date: "April 14, 2020",
    photo: "./assets/balloon-artist.jpg",
  },
  {
    title: "How To Tame a Chaotic Household",
    link: "https://slate.com/podcasts/how-to/2020/03/council-of-dads-author-bruce-feiler-on-family",
    publication: "How To!",
    date: "March 31, 2020",
    photo: "./assets/how-to.jpg",
  },
  {
    title: `How My Struggle to Breastfeed Led to Postpartum Anxiety`,
    link: "https://www.healthywomen.org/content/article/how-my-struggle-breastfeed-led-postpartum-anxiety",
    publication: "Healthy Women",
    date: "March 16, 2020",
    photo: "./assets/breastfeeding-and-ppa.jpg",
  },
  {
    title: "Life in Limbo: The Interminably Slow Pace of Adoptions",
    link: "https://bklyner.com/new-york-adoption/",
    publication: "Bklyner",
    date: "December 10, 2019",
    photo: "./assets/life-in-limbo.jpg",
  },
  {
    title:
      "Judge Judy’s Lifetime Achievement Is Teaching Us to Laugh at the Less Fortunate",
    link: "https://slate.com/culture/2019/06/judge-judys-new-york-times-profile-downplays-her-troubling-history.html",
    publication: "Slate",
    date: "June 26, 2019",
    photo: "./assets/judy.jpeg",
  },
  {
    title: "Making Room For Fathers At Hospitals",
    link: "https://bklyner.com/the-only-way-we-got-through-that-first-night-was-with-my-daughter-on-my-chest-making-room-for-fathers-at-hospitals/",
    publication: "Bklyner",
    date: "June 13, 2019",
    photo: "./assets/making-room.jpg",
  },
  {
    title:
      "How Beverly Cleary Transformed Her Harsh Childhood Into the Heartwarming Ramona Stories",
    link: "https://slate.com/culture/2019/04/beverly-cleary-ramona-authors-real-childhood-a-girl-from-yamhill.html",
    publication: "Slate",
    date: "April 11, 2019",
    photo: "./assets/cleary.jpeg",
  },
  {
    title: `Workin' Moms Offers an Infuriating, Blinkered Take on Modern Motherhood`,
    link: "https://slate.com/culture/2019/03/workin-moms-bad-motherhood-postpartum-takes.html",
    publication: "Slate",
    date: "March 19, 2019",
    photo: "./assets/workin.jpeg",
  },
  {
    title: `WHO's Language On Breastfeeding Really Is Flawed`,
    link: "https://slate.com/technology/2018/07/whos-breastfeeding-resolution-really-is-flawed.html",
    publication: "Slate",
    date: "July 10, 2018",
    photo: "./assets/who.jpeg",
  },
];
