const clips = [
  {
    title: `How My Struggle to Breastfeed Led to Postpartum Anxiety`,
    link: 'https://www.healthywomen.org/content/article/how-my-struggle-breastfeed-led-postpartum-anxiety',
    publication: 'Healthy Women',
    date: 'March 16th, 2020',
    photo: './assets/breastfeeding-and-ppa.jpg',
  },
  {
   title: 'Life in Limbo: The Interminably Slow Pace of Adoptions',
    link: 'https://bklyner.com/new-york-adoption/',
    publication: 'Bklyner',
    date: 'December 10, 2019',
    photo: './assets/life-in-limbo.jpg',
  },
  {
    title: 'Making Room For Fathers At Hospitals',
    link: 'https://bklyner.com/the-only-way-we-got-through-that-first-night-was-with-my-daughter-on-my-chest-making-room-for-fathers-at-hospitals/',
    publication: 'Bklyner',
    date: 'June 13, 2019',
    photo: './assets/making-room.jpg',
  },
  {
    title: 'How Beverly Cleary Transformed Her Harsh Childhood Into the Heartwarming Ramona Stories',
    link: 'https://slate.com/culture/2019/04/beverly-cleary-ramona-authors-real-childhood-a-girl-from-yamhill.html',
    publication: 'Slate',
    date: 'April 11, 2019',
    photo: './assets/cleary.jpeg',
  },
  {
    title: `Workin' Moms Offers an Infuriating, Blinkered Take on Modern Motherhood`,
    link: 'https://slate.com/culture/2019/03/workin-moms-bad-motherhood-postpartum-takes.html',
    publication: 'Slate',
    date: 'March 19, 2019',
    photo: './assets/workin.jpeg',
  },
  {
    title: `WHO's Language On Breastfeeding Really Is Flawed`,
    link: 'https://slate.com/technology/2018/07/whos-breastfeeding-resolution-really-is-flawed.html',
    publication: 'Slate',
    date: 'July 10, 2018',
    photo: './assets/who.jpeg',
  },
  {
    title: 'Judge Judy’s Lifetime Achievement Is Teaching Us to Laugh at the Less Fortunate',
    link: 'https://slate.com/culture/2019/06/judge-judys-new-york-times-profile-downplays-her-troubling-history.html',
    publication: 'Slate',
    date: 'June 26, 2018',
    photo: './assets/judy.jpeg',
  },
];
